# baseURL = "https://roudy.xyz/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Roudy"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  # name = "Roudy"
  # headline = "Just Roudy."
  # image = "img/author.jpg"  # path relative to static directory
  
  name = "Roudy"
  headline = "Roudy."
  image = "author.jpg"
  links = [
    { link = { href = "https://tiktok.com/@roxdy", text = "TikTok", icon = "tiktok" } },
    { link = { href = "https://instagram.com/roxdyy", text = "Instagram", icon = "Instagram" } },
    { link = { href = "https://mymun.com/profile/294920", text = "MyMUN Profile", icon = "whatsapp" } },
    { github = "https://github.com/Roxdyyy" },
    { x = "https://x.com/MEA_RXA" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
